### ISSUE TITLE
Pick a language

### ISSUE THREAD

**Issue by shmishtopher** [AndersonRobotics/Coriander#1]
What language do we want to use.  We're likely going to end up deploying on a Linux board (I have a spare Raspberry Pi Zero W).  I'm thinking C or C++.  What would y'all like to use @Samcfuchs @MichaelBenvenuto @sparklypig .

**Comment by MichaelBenvenuto** [comment]
C/C++

C but with the class keyword from C++ added.
No new keyword also no delete keyword, only malloc(), calloc(), realloc() and free()

**Comment by MichaelBenvenuto** [comment]
Pretty much C but with classes from C++

**Comment by shmishtopher** [comment]
Anyone else wanna second writing this in C?
@Samcfuchs 
@sparklypig

**Comment by sparklypig** [comment]
I don't really know either language, so I have no preference

**Comment by riverpup525** [comment]
Possibly Java? But I'm okay with whatever

**Comment by Samcfuchs** [comment]
I forgot most of my C++ knowledge. That said, java is probably not the right language for this project. How about python?

**Comment by shmishtopher** [comment]
That's not a bad idea, I'll write the HAL and open a PR for y'all to review.

**Comment by MichaelBenvenuto** [comment]
I would still recommend C/C++ over python. 

With python, each GPIO pin has to open two files from the /dev/gpio directory in linux, one to write the desired value of the selected pin and one to read the value of the pin. 
The overall system requires two files to be opened, one for setting which pin will "export" a pin (This is similar to pinMode() on an arduino) and one which will "unexport" pins.

With C, we can allocate dynamic memory which acts as a duplication of whatever memory address we want using memset(). By using memset() we can access the GPIO register from a buffer pointing to the GPIO register address in /dev/mem. This gives us not only more memory to work with (because two files per pin used wont be opened), but also increases the maximum latency of setting the value of a pin, while also allowing cross-threaded GPIO access. This option requires small include/source files with necessary bitwise arithemitic, memory safety and constants that represent register locations in memory.

I am, however, open to the idea of writing this in python.

**Comment by shmishtopher** [comment]
Using /Dev/mem would mean mapping the registers to the pins, which is not a fun task.  4.4 added a GPIO character device that we could use instead.  Does anyone know if /dev/gpiomem (not dev/mem) is platform agnostic?

**Comment by shmishtopher** [comment]
@MichaelBenvenuto Can you open a branch and make a `/dev/mem` + soft-PWM solution?  ill do the sysfs solution and we can choose the one we like better.

**Comment by shmishtopher** [comment]
Python version at #2
